### ISSUE TITLE
file.Size undefined

### ISSUE THREAD

**Issue by thanateros** [qor/media#3]
I refreshed my dependencies (`go get -u ./...` in application root) today on a QOR Admin application that has been running for weeks and now it won't start.  

`go run -v main.go` results in the error message `../../qor/media/base.go:70: file.Size undefined (type *multipart.FileHeader has no field or method Size)` .  

I noticed this repo was updated recently.

I have not edited the application in question in weeks.

I even deleted the entire local go/src/github.com/qor directory and re-pulled dependencies again and still get the same result.

What is the source of this error?  Was it the recent update?

**Comment by dbhou** [comment]
遇到了相同的问题，最近有计划更新吗？

**Comment by dbhou** [comment]
找到原因了，是因为golang版本太低导致的，go1.8会出现以上问题，升级到1.10.2，问题没有再次出现

**Comment by thanateros** [comment]
Thank you! The golang version was exactly the culprit.  I don't speak Chinese so I had to use Google Translate.  Once again, thank you.
